using Microsoft.AspNetCore.Components;
using System.Net.Http.Json;
using System.Text.Json;

namespace WebApp.Services
{
    public class AuthService
    {
        private readonly HttpClient _http;
        private readonly NavigationManager _nav;
        private const string TokenKey = "idToken";

        public string? IdToken { get; private set; } // will store id token generated by firebase
        public bool IsAuthenticated => !string.IsNullOrEmpty(IdToken);
        public event Action? OnAuthStateChanged;

        public AuthService(HttpClient http, NavigationManager nav)
        {
            _http = http;
            _nav = nav;
            IdToken = null;
        }

        public async Task<bool> LoginAsync(string email, string password)
        {
            var loginData = new { email, password };
            var resp = await _http.PostAsJsonAsync("customer/login", loginData);

            if (!resp.IsSuccessStatusCode) return false;

            var json = await resp.Content.ReadFromJsonAsync<JsonElement>();
            IdToken = json.GetProperty("idToken").GetString();
            OnAuthStateChanged?.Invoke();
            return true;
        }

        public void Logout()
        {
            IdToken = null;
            OnAuthStateChanged?.Invoke();
            _nav.NavigateTo("login");
        }

        public void AttachToken(HttpRequestMessage request)
        {
            if (!string.IsNullOrEmpty(IdToken))
                request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", IdToken);
        }
    }
}
